---
apiVersion: v1
kind: Service
metadata:
  name: cgrmanager-service
  namespace: ricc-dev-itsyscom
spec:
  type: NodePort
  selector:
    app: cgrmanager
  ports:
    - name: jsonrpc
      port: 2012
      targetPort: 2012
      nodePort: 32012
    - name: http
      port: 2080
      targetPort: 2080
      nodePort: 32080