---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  storageClassName: robin
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /export/cgrtps/data
    server: "[240b:c0e0:101:5582:ac00:2:0:a]"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - uhn7kls1arbwk001.rmnkiba.local
          - uhn7kls1arbwk002.rmnkiba.local

  claimRef:
    name: redis-pvc
    namespace: ricc-db-redis


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: ricc-db-redis
spec:
  storageClassName: robin
  volumeName: redis-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
